version: '3.8'

services:
  web:
    build: ./web
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build: ./backend
    expose:
      - "3000"
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Docker 소켓 공유
      - libc_data_volume:/usr/src/libc-data # libc-data 볼륨 공유 (변경됨)
      - upload_volume:/usr/src/uploads # 업로드 볼륨 공유 (변경됨)
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock # Docker 엔진 소켓 설정
    restart: always # backend가 종료되면 자동 재시작

  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: myroot
      MYSQL_DATABASE: docker_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: myuser
    volumes:
      - ./DB_Extract:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pmyroot"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always # db가 종료되면 자동 재시작

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  libc_data_volume: # 파일 지속을 위한 새로운 볼륨
  upload_volume: # 업로드 파일 지속을 위한 새로운 볼륨